name: Build kernel

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'sixteen'

jobs:
  build_lavender:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [SM-G9980]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update -y
          sudo apt install -y android-tools-mkbootimg build-essential libssl-dev bison flex libelf-dev bc cpio git zip unzip

      - name: Fetch Clang Toolchain
        run: |
          git clone https://github.com/yanzihan/clang-r547379 --depth=1 clang
          
      - name: Fetch AnyKernel3
        run: |
          git clone https://github.com/yanzihan/AnyKernel3 -b samsung ./AnyKernel3
          
      - name: Build Kernel Clean
        run: |
          source ./build_sm8350.sh ${{ matrix.target }}
          cp ./AnyKernel3/Lavender* ./

      - name: Clean Kernel Source
        run: |
          make mrproper ARCH=arm64 LLVM=1

      - name: Build Kernel With KSU
        run: |
          source ./build_sm8350.sh ${{ matrix.target }} --ksu
          cp ./AnyKernel3/Lavender* ./

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            boot.img
            dtbo.img
            Lavender*.zip
          name: Kernel-CI_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Kernel: 5.4.274
            Clang: AOSP clang-r547379
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
